name: Delete completed workflows

on:
  workflow_call:

jobs:
  purge:
    name: Delete completed workflows
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Purge completed
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const completed = await github.rest.actions.listWorkflowRunsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 100,
            status: 'completed',
          });

          for (const job of completed.data.workflow_runs) {
            console.log(`Deleting run id ${job.id} of '${job.name}'`);
            try {
              await github.rest.actions.deleteWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: job.id
              });
            } catch (error) {
              // ignore errors
            }
          }

